### ISSUE TITLE
Следует уточнить формулировку метагейма

### ISSUE THREAD

**Issue by volas** [TauCetiStation/Rules#1]
По сравнению с текущими правилами и подходами.

Более подробное обсуждение было на форуме http://tauceti.ru/forums/index.php?topic=6930.0

**Comment by volas** [comment]
Да, при всём этом следует еще участь и уточнить крайние случаи в других правилах (манч, повергейм).

**Comment by dred1792** [comment]
Если и менять, то нужно идти рука об руку с этой темой #6.

**Comment by Belfogor** [comment]
Я бы не стал менять формулировку метагейма, да и отозвавшиеся в теме оценили эту инициативу больше негативно, чем позитивно. Просто возникает один большой вопрос, где же теперь будут эти самые рамки. В не далеком будущем почва для дальнейших конфликтов. Оптимальный вариант было бы перекрыть эту проблему механом. Раз и навсегда.

**Comment by volas** [comment]
Тут просто не нужны рамки, как уже с тобой обсуждалось - большинство, если не все, действительно критичных ситуаций покрывается другими правилами.  
Но еще стоит закрепить где-то мысль, может в правилах персонажа, что не следует выполнять работу, если на неё уже кто-то назначен (не ломиться поднимать сингу если есть инженеры и т.д.)

**Comment by dred1792** [comment]
В правилах персонажа есть подобный пункт,
