### ISSUE TITLE
[Предложение] Сумасшествие персонажей

### ISSUE THREAD

**Issue by Gittanley** [TauCetiStation/Rules#12]
"Отыгрывайте реалистичных и естественных персонажей в соответствии с лором игры (в том числе в соответствии с профессией, расой, режимом игры).
Если ваш персонаж - псих с маниакальной тягой к убийству/самоубийству, то у нас для вас плохие новости..." Взято с вики, правила.
Стоит добавить что-то вроде "На станцию попадают психически здоровые люди". С другой стороны, будет ли держать НТ ценного сотрудника(например, опытного ученого), с гиперциновой зависимостью? 
Или например, когда ассистент, лет 25, приходит на станцию, там кишки, кровь, и прочее, от чего нормальный бы человек блеванул и наверное, сошел с ума, наш же ассистент, идет спокойно, будто бы это обыденные вещи(в рамках сервера, действительно обыденность).

P.S Вообще, это очень сложная тема, ведь это психология, особенно, социальная.

**Comment by Kortez90** [comment]
От гиперцина, кажется, нет зависимости.
У вас какие-то киношные клише, что люди вдруг блюют на пол, если по стенам кровища размазана.
И тема это вполне обычная. Перед попаданием на станцию сотрудники действительно должны проходить медицинское обследование, которое включает в себя также осмотр психолога. Исключением были лысики, которых использовали как мясо (то бишь D-Class). Проблема в том, что гамма, люди и хост. Большому кол-ву школьников нужна не игра, а мясорубка, где можно скрафтить из железного прута и батарейки пушку, чтобы ходить и отстреливать антагов, либо персонал. С другой стороны хост, который стремится к большому кол-ву наркоманов на сервере и для него нет разницы, будут ли они играть в ss13 или грифонить ее. Так что подобный пункт правил ATM вообще смысла почти не имеет, но на псевдо-тиранской классике подошел, если бы состав педалей не был столь кислотным. Впрочем, даже на классике люди не пользовались документацией ни к их месту работы, ни к персоналу с которым работали.
