### ISSUE TITLE
[Предложение] Правила ксеносов

### ISSUE THREAD

**Issue by volas** [TauCetiStation/Rules#2]
Давно обсуждал с ксеновизорами, но пока так не пришли к соглашению.  
Идея в том, что каждой расе требуется список критериев, конкретно за нарушение которых отбирают хвост.  
Потому что сейчас это происходит очень неявно и не очевидно, по субъективному мнению ксеновизора. Не понравился ксеновизору отыгрышь - долой хвост :scream_cat:  

---

Вместе с тем, возможно стоит закрепить в правилах, что хвост не даёт никаких преференций по отношению к правилам. К примеру, если ты играешь за ящера, то "природная агрессия" никак не будет учитываться в конфликтных ситуациях и будет разбираться аналогичным ситуациям "человек-человек". Частично затрагивалось на форуме тут: http://tauceti.ru/forums/index.php?topic=6609.msg111096#msg111096  
Это поможет избежать неоднозначных ситуаций из-за различных трактовок бэка и просто думаю будет справедливо.
**ЛИБО** альтернативное решение - аналогично как в первой половине, зафиксировать список где какие вольности доступны ксеносу.

**Comment by dred1792** [comment]
Полностью за список основных критериев, за нарушение которых можно лишиться хвоста.

**Comment by Belfogor** [comment]
Фактически весь этот список существует в беках ксеноты, но лишним не будет продублировать его отдельно в правилах, чтобы окончательно расставить все точки над и.

**Comment by AgRevol** [comment]
Практически с самого начала моего ксеновизорства я расписал базовый список для таяран, унатхов и дионея. При чём у вторых, собственно, есть комментарий (выделенный жирным текстом), что ксенораса - не причина для грифа. Практики "Не понравился ксеновизору - лишился хвоста" избавились практически сразу с уходом Совка4, сейчас мгновенно лишиться хвоста можно только творя откровенный брэйнрот либо полностью игнорируя отыгрышь и бэк расы. В остальных случаях проводится разговор и работа над ошибками.

**Comment by TungstenOctopus** [comment]
И правда, зачем учитывать "природную агрессию", можно вообще удалить бэк и механоразличия, чтобы ящеры, к примеру, отличались от людей только спрайтом. Это будет справедливо!
