### ISSUE TITLE
Правила ИИ

### ISSUE THREAD

**Issue by volas** [TauCetiStation/Rules#3]
Часто возникают неоднозначные ситуации из-за трактовок законов ИИ. И вообще там множество неоднозначных ситуаций бывает.
Можно перенять идею с tg о отдельном разделе, посвященном силиконам https://tgstation13.org/wiki//index.php?title=Rules#Silicon_.28and_Drone.21.29_Policy

**Comment by Belfogor** [comment]
Да надо бы. Только вот никак не дойдут ни у кого руки. Где же этот герой.
