### ISSUE TITLE
Антагонисты. Пункт 2. Профильные знания.

### ISSUE THREAD

**Issue by Leshiy-ART** [TauCetiStation/Rules#33]
```
2. На антагониста в меньшей степени распространяются правила, касающиеся внутриигровых знаний персонажа.
Для подготовленного агента синдиката, напичканного имплантами биоробота или же ксеноса, занимающегося пожиранием людей и присвоением их личностей на регулярной основе, абсолютно нормально обладание знаниями любой станционной профессии, кем бы они ни были изначально.
С другой стороны, массовые, приобретаемые в раунде роли (культисты, треллы, революционеры) как правило получают только свои профильные знания, если они есть.
```

Вопрос вызывает весь пункт правил. На данный момент любой сотрудник может обладать знанием всех профессий, и ограничен он только 4-м правилом персонажа.
О каких "профильных знаниях" идет речь в последнем пункте?

Больше похоже на то, что данный пункт либо совсем больше не нужен, либо его стоит переписать на знания о других антагонистах.
Например в пункте о "одиночных" ролях написать что знание о других антагонистах - это нормально.
А в пункте о массовых ролях - что люди получают знания только о своей роли.
(культист получает знания о культе, трелл о новом способе общения и целях мастера, и так далее)

**Comment by skvazarb22** [comment]
Контекст, где понятие "знаний" могло толковаться неоднозначно, больше не существует. Ишью можно считать неактуальным.

**Comment by Leshiy-ART** [comment]
Да, закрываю.
