### ISSUE TITLE
Селфантагинг

### ISSUE THREAD

**Issue by volas** [TauCetiStation/Rules#4]
Это давняя политика администрации - если человек просит в ПМ о чуть больших возможностях (даже о нарушении правил), то по обстоятельствам ему разрешают/даже помогают с реализацией задумок.
На зарубежных станциях тоже есть подобный опыт, и они зафиксировали это в правилах https://nanotrasen.se/forum/topic/9646-server-rules/ (искать по Self Antagging)

У нас через ПМ это было сделано только для возможности контролировать количество событий в раунде, подробнее тут: http://tauceti.ru/forums/index.php?topic=5908.0

Можно обсудить еще раз и тоже зафиксировать в правилах.

P.S. Кстати, :cookie: тому, кто подберёт хорошую альтернативу названию на русском!

**Comment by dred1792** [comment]
Внезапно, но мне кажется, что можно так и оставить - Селфантагинг.

**Comment by Belfogor** [comment]
Это можно просто где-то дополнительно закрепить, но я думаю что опытные игроки и так понимают, что если у них есть желание выйти за рамки, стоит сперва проинформировать об этом активного администратора и согласовать с ним, чтобы после самому не получить по шапке.
