### ISSUE TITLE
Закрепить точку зрения админа в игре, даже если он не прав

### ISSUE THREAD

**Issue by volas** [TauCetiStation/Rules#5]
Это частая проблема, когда админ просит игрока что-то не делать, а игрок не соглашается/начинает спорить/флеймить. Либо споры после применения наказания.

Проблема в том, что в игре это делать крайне неудобно, там может отсутствовать старший стафф, и в 99% случаев попыток таких обсуждений по горячим следам игрок скорее загонит себя в бан, чем решит проблему (хотя у админов есть инструкция несколько раз попросить перенести обсуждение на форум, прежде чем применять меры).  
Постфактум всё можно обсудить на форуме, в спокойной обстановке, с привлечением других необходимых админов.

**Comment by dred1792** [comment]
Даже не знаю, это может стать причиной пресловутого "Админ всегда прав!", что ни есть хорошо. Я бы предпочёл оставить всё как есть на этот счёт.

**Comment by volas** [comment]
Можно тогда переформулировать в "Не спорь с админом в игре".  
Суть в том, что бы любые спорные ситуации выносились на форум и там обсуждались. Может всплывут недоработки в вики, в правилах, еще что-то.

**Comment by TungstenOctopus** [comment]
Тогда зачем вообще писать ПМ? Можно сразу банить, ведь в игре спорить и доказывать свою правоту нельзя.

**Comment by volas** [comment]
Это не вахтерства ради, а нормальных обсуждений и избегания ингейм срачей. У нас в текущих правила данная мысль уже присутствует, но где-то внизу и не все добираются.

Для справки, оформление в зарубежных сообществах:
[/tg/](https://tgstation13.org/wiki//index.php?title=Rules)
>6. In-game administration rulings are final.
    Incidences of admin abuse, negligence or disputed rulings can be taken to the forums. If an admin says something was 'looked into, handled, resolved' etc, regarding an issue, it is unlikely an admin will provide any further information. Admins are under no obligation to reveal IC information. Deliberately lying or misrepresenting facts in adminhelps will be dealt with harshly. 

[Baystation](https://tgstation13.org/wiki//index.php?title=Rules)
>2. Listen to staff
    2.1 The word of the staff is law.
    2.2 If you disagree with a ruling, bring it up after the round with the staff member, the staff manager, or via official complaint.
    2.3 If a staff member is blatantly abusing this rule, then we urge you to contact a senior immediately, or if necessary, file an official complaint.

[Paradise](https://nanotrasen.se/forum/topic/9646-server-rules/)
>Rule 1: Listen to the Admins
The Staff Members have final say on the server. If you are banned or job banned from the server, you are to write an appeal instead of continuing the conversation via Adminhelp or Discord messages.
The Adminhelp system is not to be spammed. If you do not get a response, the Administrators are either busy with other matters or not available.
If no Administrators are available, you may take your request to the forums if needed. If an Administrator asks you to stop arguing over the in-game PMs, you must stop but may take it to the Review Board;
We hold the right to deem a Ckey inappropriate to the server and can ask you to make a separate account to log in with. Examples of inappropriateness include, but are not limited to, excessive vulgar language, bigotry or references to real life celebrities;
When in doubt, Adminhelp any question you may have about the Server Rules.

**Comment by Belfogor** [comment]
Ключевой акцент тут делается на словах "в игре". То есть. Во избежания пререканий между игроком и администратором во время раунда, что отвлекает обоих. И по собственному опыту хочу сказать, что обычно такие споры оканчиваются ровно ничем. И игрок и администратор остаются каждый при своем.  И по завершению раунда, если игрок все еще считает что действия администратора были неправомерны или несправедливы, игрок сможет вынести суть своей жалобы на форум, где обе стороны смогут изложить свои доводы в спокойной обстановке и на холодный зад, с привлечением внимание общественности и других администраторов, которые их и рассудят. 

И Волес прав. Такая практика является нормальной на всех известных мне зарубежный серверах и призвана она разгрузить модератора.

**Comment by TungstenOctopus** [comment]
Тогда, опять же, можно сразу написать "Извините вы его убили неправильно и ни за что, вам бан", дать бан. Ведь "In-game administration rulings are final", и зачем выслушивать игрока, если ты уже решил что он виновен?

**Comment by RichardJones1** [comment]
А вдруг он не понял своей ошибки? Нужна сто процентов беседа, желательно ингейм, чтобы рассказать игроку, как и что он сделал не так. Ну, я так считаю.

**Comment by Skippeer12** [comment]
Это бы сработало, если бы на форуме классики жалобы не проходили модерацию неделю или месяц, после чего их бы не закрывали за сроком давности или истёкшим сроком бана. А как мы все прекрасное знаем, форумных кукаретиков никто слушать не будет (с) . Так что это игра в один ворота.

**Comment by EdlerN** [comment]
В сущности, нет особой разницы, кто пишет жалобу, если она обоснована. Что до скорости реакции на них - определенные меры уже были предприняты.
И, да. Если подобное правило будет закреплено - значит любые подобные просьбы со стороны администратора получают статус административного вмешательства. А проебы в этой сфере как правило рассматриваются куда как более серьезно и меры в этом отношении будут предприниматься соответствующие.

**Comment by volas** [comment]
>А вдруг он не понял своей ошибки? Нужна сто процентов беседа, желательно ингейм, чтобы рассказать игроку, как и что он сделал не так. Ну, я так считаю.

Это не отменяет беседы, она обычно проводится по необходимости. Это лишь покрывает ситуации, когда игрок намерен по пол часа "отстаивать свою точку зрения" в ПМ.

>Так что это игра в один ворота.

Как пример, были жалобы на вмешательство в игру, по итогам хедмином была поднята проблема о отношении игроков в подобному http://tauceti.ru/forums/index.php?topic=6818.0  
В идеале так и должны работать обсуждения. Всплыло разногласие ингейм, человек пишет жалобу, по обсуждениям выискиваются проблемы, если это не вина игрока или админа - поднимать отдельное обсуждение о проблеме.  
В прошлом по жалобам так же поднимались проблемы, но обсуждались лишь среди админов.  

А если игрок не напишет жалобу, то в лучшем случае проблема просто не выйдет за рамки игры. В худшем, если игрок будет спорить, получит бан (даже если игрок будет прав на 146%, за пререкания в игре действия со стороны админа будут справедливы).
