### ISSUE TITLE
"Святые" офицеры

### ISSUE THREAD

**Issue by volas** [TauCetiStation/Rules#51]
https://github.com/TauCetiStation/Rules/blob/master/index.md#L129-L130

```
1. Офицер службы безопасности — дисциплинированный боец, который прошел тщательный отбор. Они являются первым и последним рубежом защиты станции. Силой, которая призвана поддерживать внутренний порядок на борту станции и способствовать сохранению корпоративных интересов, в числе прочего служить их законным представителям, то бишь главам.   
   - Соблюдайте [иерархию приказов](https://wiki.taucetistation.org/Standard_Operating_Procedure#Иерархия_приказов). Постарайтесь максимально ответственно отнестись к выполнению поставленных вам задач.  
```

Следует поправить данную формулировку. В контексте скорее говорится про ответственность профы, что она не для новичков, и что человек должен знать все эти СОПы/иерархию/прочую ic хрень.

Но в текущей формулировке может восприниматься как запрет на отыгрыш "плохих парней", коррупционеры и прочее.

**Comment by f8upd8** [comment]
Я предлагаю убрать раздел "Офицерам службы безопасности" из правил, так как раздел содержит общие рекомендации офицерам, которые сильно ограничивают их игру и дают широкий спектр для интерпретации и спекуляции. У офицеров нет импланта лояльности, они являются охранниками, нанятыми корпорацией в целях защиты своих интересов. Насчёт харма - есть правила про конфликты. Насчёт иерархии - есть правило про иерархию. Касательно антагонистов у нас есть правило про повергейм. От данного свода правил одни неудобства.

**Comment by skvazarb22** [comment]
В контексте очевидно говорится не только о необходимости знать всякую IC хрень, но и о том, что с них повышенной спрос за доступ к пушечкам. Часть про иерархию дублирует общие правила для персонажей и от нее можно без проблем избавиться. В остальном я не очень понимаю где именно там можно прочитать запрет на отыгрыш плохих парней, потому что никаких злых стоп про запреты в этих формулировках нет. 

Свобода персонажей отдельно оговаривается

>1. Если игра не выдала вам роль антагониста — вы не являетесь им. Это, впрочем, не запрещает вам быть коррумпированным главой/офицером, красть, заниматься мелкими грабежами и тому подобным. Однако, следует придерживаться некоторых рамок. В общем случае правило следующее — целью ваших действий не должно быть надолго вывести другого игрока из игры. Вашей целью не должны быть предметы высокого риска и некоторые уникальные предметы, отсутствие которых может сказаться на развитии раунда. Если вас застукали — вы не должны эскалировать ситуацию. Помимо этого, хорошим тоном будет предварительно уведомить Администрацию о своих намерениях.

Безусловно прямые противоречия с этим пунктом следовало бы устранить, но я их не вижу.

**Comment by skvazarb22** [comment]
@volas, я не до конца понимал основной тезис этого ишью, но в #58 обсуждаемый пункт был практически полностью переделан, поэтому, возможно, этот ишью уже не актуален.
