### ISSUE TITLE
Денежный счёт департамента. 

### ISSUE THREAD

**Issue by Arronakks** [TauCetiStation/Rules#54]
Играя за КМ, в ноутах увидел номер своего аккаунта и номер аккаунта самого Карго. Они разные, с разными паролями. Но оба ведут именно в мой аккаунт, в аккаунт департамента нельзя попасть.

**Comment by Motzord** [comment]
>Вставляешь свою карту
>Вводишь номер и пин департамента
>профит

/thread

**Comment by Arronakks** [comment]
> > Вставляешь свою карту
> > Вводишь номер и пин департамента
> > профит
> 
> /thread

Раньше так и делал, но получалось так, как рассказал. Только что попробовал и получилось. Может что то и я не так сделал.
