### ISSUE TITLE
Не точное формулирование правила о "Ядерной угрозе/Нюке"

### ISSUE THREAD

**Issue by Avatar4** [TauCetiStation/Rules#56]
В данный момент, в правилах подразумевается только то, что нюкеры могут любыми средствами аннигилировать но не забывать и о основной цели. Однако в обсуждении на [форуме](https://forum.taucetistation.org/t/snyatie-rp-ogranichenij-na-protivostoyanie-nyuki-i-ekipazha/12502), и в правке правил подразуевается и то, что экипаж тоже может любыми способами противостоять нюке (то бишь, павергейм и реалистичность персонажа не считаются).

Вот так гласит правило которое установлено на сайте правил:
"Для оперативников режима “Ядерная угроза” война со станцией является частью режима, так что к вам не будет претензий в случае тотальной аннигиляции экипажа. Но не стоит слишком увлекаться в ущерб основной цели (взрыв станции). Затянувшийся раунд, где веселятся только пара антагонистов, напрочь игнорируя цели завершения раунда, будет не очень интересен другим игрокам и может вызвать вопросы у администрации."

А так, как его по идее должны были добавить:
"Режим Нюка: соответствии с обсуждением на форуме нюкерам разрешено аннигилировать станцию и экипаж по своему усмотрению, для экипажа же сопротивление оперативникам является достаточной мотивацией и не будет ограничиваться правилами повергейма/реалистичности персонажа (#32)"

**Comment by skvazarb22** [comment]
Раздел, в котором находится это правило, называется "Особые положения для некоторых ролей", а конкретный пункт "Антагонисты". Пояснять поведение остального экипажа там неуместно, нелогично и не нужно.

**Comment by skvazarb22** [comment]
Решено в #32, можно закрывать.
