### ISSUE TITLE
Педальное вмешательство

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [TauCetiStation/Rules#62]
> Слушайте, то что вам говорит Администратор.
Если вас официально попросили что-то прекратить, или наоборот сделать — это имеет силу правила.
В случае пренебрежения этим правилом администрация оставляет за собой право выдать вам наказание вплоть до суточной блокировки ссылаясь на этот пункт.
Главным образом от вас ожидается информация по ситуации и вашей мотивации в том или ином случае.
Учтите, что в некоторых случаях информация на вики может оказаться неточной или устаревшей.

По сути администратор любого ранга может временно создавать правила для создания выгодных условий для себя и определённых игроков.

Это очень плохое правило и пережиток педальной тирании. На свободном сервере игрок должен быть всегда прав пока он не нарушает правила, а сами правила не должны конкретно определять правоту одной из сторон. Поэтому я предлагаю немного изменить саму концепцию администраторов, а именно забрать у них карт бланш на любую возможность контроля событий в раундах (наверное, ивенты здесь будут исключениями). Вместо этого они будут следить за соблюдением игроками правил, а сами правила сформировать таким образом чтобы позволить игрокам быть максимально свободными в плане отыгрыша без вреда свободам других и обеспечить их максимально возможным комфортом.

Также я хотел бы формально ввести в правила т. н. принцип согласия, а именно запрет на применение наказаний к игроку если на него не поступали жалобы от непосредственно пострадавших игроков.

**Comment by volas** [comment]
> Это очень плохое правило и пережиток педальной тирании.

Всё в порядке, у этого правила есть контекст, просто нужно прочитать их до конца.
tl;dr администратор говорит и действует под свою ответственность, на него могут пожаловаться на форуме, если администратор оказался не прав с точки зрения старшей администрации - ему попадёт. Но в раунде бодаться с администратором не нужно - это контрпродуктивно и не несёт никакой пользы. Даже если игрок прав, а админ нет - в рамках раунда игрок ничего админу не сделает и может только получить еще больше и уже по заслугам за засорение ахелпа.
