### ISSUE TITLE
Удалить самое ненужное правило

### ISSUE THREAD

**Issue by cool20141** [TauCetiStation/Rules#63]
![image](https://user-images.githubusercontent.com/53309265/91657544-7a0a2500-eaca-11ea-8a51-088b726332ea.png)
Ужаснейшее правило. Скажет админ ливнуть тебе с сервака–ты ОБЯЗАН будешь по правилам ливнуть, а иначе бан :)
Скажет тебе сделать еще какую-нибудь дурость–сделаешь. Иначе бан. И да, не надо говорить, что никто этим не пользовался, не пользуется и никогда не воспользуется, потому что сам с подобной ситуацией сталкивался, когда нарушения не было, но админ захотел доебаться
Ну и как бы очевидно, что администратора нужно слушаться, потому наличие в правилах такого пункта не требуется, другое дело, что я не должен делать все, о чем меня эти админы попросят

**Comment by cool20141** [comment]
Если что, 100% серьезно написано, потому что некоторые думают(админы), что это шутка(власть боятся потерять)

**Comment by EdlerN** [comment]
Идиотия продолжается. Администратор может просто дать тебе бан и ты ничего с этим не сделаешь. Другое дело что такие просьбы являются административным вмешательством и администратор несёт за такое вмешательство ответственность. И на такое вмешательство можно жаловаться. На форуме. А не в игре. Потому что в игре ты всё равно ничего не сделаешь. Более того, такие любители поспорить только затрудняют и так нелёгкую работу администратора. Поэтому существует данное правило.

**Comment by volas** [comment]
Ух, еще один.
https://github.com/TauCetiStation/Rules/issues/62#issuecomment-683265777

**Comment by cool20141** [comment]
Ясно, админ затиранил, господин вахтер aka EdlerN, вы, видимо, сами пользуетесь этим правилом на постоянной основе(Когда присутствуете в игре), чтобы смеяться над бедными игроками, которым приходится выполнять глупые, а иногда, полагаю, унизительные просьбы с вашей стороны. Если это так, то понятно, по какой причине вы так защищаете это глупое правило

**Comment by cool20141** [comment]
И да, насчет того ответа–это было сказано на гитхабе, но нигде конкретно в правилах об этом нет(Есть что-то про форум, но это явно не то)

**Comment by EdlerN** [comment]
> И да, насчет того ответа–это было сказано на гитхабе, но нигде конкретно в правилах об этом нет(Есть что-то про форум, но это явно не то)

Ohrly?

![image](https://user-images.githubusercontent.com/26942612/91657923-c2771200-eacd-11ea-996a-f2ab10c3243a.png)
![image](https://user-images.githubusercontent.com/26942612/91657927-d15dc480-eacd-11ea-93ba-58a7f94ce60a.png)

**Comment by cool20141** [comment]
Ну я правила не читал, собственно, ко мне какие вопросы?

**Comment by Ambassadoing** [comment]
> Ну я правила не читал, собственно, ко мне какие вопросы?

Зачем ты тогда разводишь эту клоунаду?

**Comment by cool20141** [comment]
Потому что тупое правило
